# Generated by Django 5.0.4 on 2024-04-11 16:36

from django.db import migrations
from apps.blog.models import BlogCategory


def add_blog_categories(apps, schema_editor):
    categories = [
        'Новости',
        'Обзоры',
        "Акции",
        "Партнерам",
        "Специальные предложения",
    ]
    for category in categories:
        BlogCategory.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_options_alter_article_tags'),
    ]

    operations = [
        migrations.RunPython(add_blog_categories)
    ]
