# Generated by Django 5.0.4 on 2024-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_blog_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/category/', verbose_name='Изображение'),
        ),
    ]
