# Generated by Django 5.0.4 on 2024-04-16 16:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/category/', verbose_name='Изображение'),
        ),
    ]
