# Generated by Django 5.0.4 on 2024-04-16 16:31

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_article_category_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='blog/article/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='blog/category/', verbose_name='Изображение'),
        ),
    ]
